name = "ChinaZen"
license = "MIT"
licenselink = "https://github.com/natarajmb/charaka-hugo-theme/blob/master/LICENSE.md"
description = "Minimalistic and Responsive blog theme for hugo"
homepage = "https://github.com/junlv/china-zen-theme"
tags = ["personal", "blog", "simple", "clean", "minimalist", "highlight.js", "jssocials", "font-awesome", "bluma"]
features = ["html5", "css3", "highlight.js", "jssocials", "responsive"]
min_version = 0.46

[params]

[author]
  name = "at719"
  homepage = "https://www.at719.com"
